# Generated by Django 4.0.6 on 2022-07-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_expense_repeat_next_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expenses'),
        ),
    ]
