# Generated by Django 4.1 on 2022-08-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_banks_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='sheets.banks'),
        ),
    ]
