# Generated by Django 4.1 on 2022-08-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0009_expense_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banks',
            name='color',
        ),
        migrations.AlterField(
            model_name='banks',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
